name: Super-Linter
on: 
  push   

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest  # ✅ Fixed `runs-on`
    steps:
      - name: Checkout Code  # ✅ Fixed spacing issue
        uses: actions/checkout@v2  # ✅ Fixed indentation

      - name: Run Super-Linter  # ✅ Fixed spacing issue
        uses: github/super-linter@v4  # ✅ Corrected indentation

